2025-09-07 13:42:57,938 |    ERROR | clever_ai | error:128 | [ERROR_RECOVERY] Error occurred | Data: {"context": {"integration_test": true}} | Error: Integration test error
2025-09-07 13:42:57,938 |    ERROR | clever_ai | error:129 | Traceback: NoneType: None

